In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [4]:
arr[:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
arr[0:5]= 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [9]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [10]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [11]:
arr_copy = arr.copy()

In [12]:
arr_copy[:] = 100#This method creates a copy of an array object.
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [13]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [14]:
arr_2d = np.array([[20,48,37],[77,97,102],[10,20,40]])
arr_2d

array([[ 20,  48,  37],
       [ 77,  97, 102],
       [ 10,  20,  40]])

In [15]:
arr_2d.shape

(3, 3)

In [16]:
arr_2d[0,2]

np.int64(37)

In [30]:
arr_2d[:2,1:]#slicing in n-1

array([[ 48,  37],
       [ 97, 102]])

In [45]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [47]:
bool_arr = arr > 4 

In [48]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [49]:
arr[bool_arr]#it gives the number value

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])