In [1]:
import numpy as np

In [2]:
my_list =[1,2,3]
type(my_list)

list

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_arr = [[1,2,3],[2,3,4],[8,9,10]]
np.array(my_arr)

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 8,  9, 10]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(1,100,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.linspace(1,100,7)

array([  1. ,  17.5,  34. ,  50.5,  67. ,  83.5, 100. ])

In [24]:
np.random.rand(2,5)

array([[0.11451067, 0.16875438, 0.68013923, 0.54980347, 0.02892185],
       [0.12918738, 0.5210466 , 0.38175095, 0.19175971, 0.19033422]])

In [26]:
np.random.rand(5)

array([0.84910059, 0.72852559, 0.02112695, 0.50423368, 0.06783472])

In [31]:
np.random.randn(2,5)

array([[-0.14559468, -0.56425256, -0.18452915,  0.29608449,  0.6452845 ],
       [-0.20005693,  1.3438505 ,  0.52642877, -0.952762  , -0.24222208]])

In [32]:
np.random.randn(5)

array([ 1.86384805, -0.30257688,  1.41987082, -2.45981341,  1.18865378])

In [33]:
np.random.seed(12)
np.random.rand(5)

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496])

In [39]:
np.random.seed(12)
np.random.rand(5)

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496])

In [45]:
arr = np.arange(0,25)
ranarr = np.random.randint(0,100,10)

In [50]:
arr.shape

(25,)

In [47]:
ranarr

array([76, 13, 82, 89, 35, 62, 35, 33, 30, 63], dtype=int32)

In [49]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])