In [13]:
import numpy as py

In [14]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [15]:
type(my_list)

list

In [27]:
np.array(my_list)

array([1, 2, 3, 4])

In [28]:
my_arr = np.array(my_list)
my_arr

array([1, 2, 3, 4])

In [29]:
type(my_arr)

numpy.ndarray

In [30]:
my_matrix = [[1,3,4 ],[1,4,5],[7,8,9]]
type(my_matrix)

list

In [32]:
mymatrix_arr = np.array(my_matrix)
mymatrix_arr

array([[1, 3, 4],
       [1, 4, 5],
       [7, 8, 9]])

In [33]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [35]:
np.zeros(5)#it produces 1 dimension vector of zeros

array([0., 0., 0., 0., 0.])

In [36]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [37]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [41]:
np.linspace(1,10,5)#it give linearly space bw n to n-1 and last is how much space len


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [43]:
np.eye(5)#it give identity matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
np.random.rand(5,3)#it print random value of 0 to 1 of 2d array# np.random.rand(d0, d1, ...) 
#   -> Generates random numbers **between 0 and 1** (uniform distribution)
#   -> Numbers are equally likely anywhere in the range [0, 1)
#   -> Example: np.random.rand(3) might give [0.12, 0.55, 0.99]

array([[0.74814483, 0.31634274, 0.77523194],
       [0.36261407, 0.52317491, 0.21847726],
       [0.83674936, 0.42734529, 0.93584129],
       [0.36031554, 0.86467841, 0.15777016],
       [0.68807573, 0.36837054, 0.81799459]])

In [57]:
np.random.rand(5)#it print value of 1 d array

array([0.20193174, 0.18207615, 0.79122144, 0.29890022, 0.59869909])

In [58]:
np.random.randn(5,2)# np.random.randn(d0, d1, ...) 
#   -> Generates random numbers from **standard normal distribution** (Gaussian)
#   -> Mean = 0, Standard Deviation = 1
#   -> Most numbers are near 0, can be positive or negative
#   -> Numbers are NOT limited to 0–1; some can be >1 or <-1
#   -> Example: np.random.randn(5) might give [-0.45, 1.23, -0.89, 0.67, 0.12]
#   -> Use scaling to get desired mean and std: new_array = mean + std * np.random.randn(size)

array([-0.05644047, -0.02614031, -0.36574713, -2.10150656, -0.13277472])

In [60]:
np.random.randint(0,101,5)#it gives random number between 0 to 101

array([59, 97,  8, 43, 42], dtype=int32)

In [62]:
np.random.randint(0,101,(2,5))# it print in 2d array

array([[94, 76, 21, 54, 56],
       [39, 20, 26, 53, 22]], dtype=int32)

In [63]:
np.random.seed(50)#it give same random number always seed 50 has key to call same random number in other terminal
np.random.rand(5)

array([0.49460165, 0.2280831 , 0.25547392, 0.39632991, 0.3773151 ])

In [72]:
arr = np.arange(0,25)#it reshape all the array elements
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
ranarr = np.random.randint(0,100,10)
ranarr

array([68, 78, 35, 92, 91, 26, 90,  6, 20, 43], dtype=int32)

In [77]:
ranarr.max()

np.int32(92)

In [78]:
ranarr.min()

np.int32(6)

In [80]:
ranarr.argmax()

np.int64(3)

In [81]:
ranarr.argmin()

np.int64(7)

In [83]:
ranarr.dtype

dtype('int32')

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [86]:
arr.shape

(25,)

In [88]:
arr = arr.reshape(5,5)
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [89]:
arr.shape

(5, 5)